### ISSUE TITLE
Follow JNC

### ISSUE THREAD

**Issue by emmilydev** [DiegoNighty/HTTP-Wrapper#1]
In <a href="https://github.com/DiegoNighty/HTTP-Wrapper/blob/main/src/main/java/com/github/diegonighty/http/HttpConnection.java">HttpConnection</a>, you don't follow the Java Naming conventions for the enum constants. You can add a String parameter to the constructor, and the use it in the parse() method.

**Comment by diegonighty** [comment]
It has already been fixed, thanks for the issue
